---
language: node_js
node_js:
- 0.6
- 0.7
- 0.8
env:
  global:
  - secure: ! 'aZ4iFCwPReSO+CgjbTb++VxwCCSyjYPegLz1XrpRgLWJxdYY6Ap/3HfWLg+C

      GNFOwnCJ5UvjrdR+gemEx9VxtVh2cqeeBzy+vPYFnpBbjvOiHPZm3Fa7z5vs

      KIAZlpaMozffPC73qbiizpd4wFJwc78l6BaKzOf7ol4sPevmDCQ='
