---
language: node_js
node_js:
- 0.6
- 0.7
- 0.8
env:
  global:
  - secure: ! 'QhbL/gvLogkQE/78+er5XudZKD0rqa1MhI5nY+Uk4T7+YaubIKgS2grB434r

      FOYxUwwW123perX0rPTBcBKoOBfGHWjHGNCBuSMVeF/lmIhx5asxjegcUILF

      JMlzlqJJMNiGZ18JOeUwBsNRBJhbvUCs8DQb9BJRgu0LYrPA3ws='
